spring:

  application:
    name: omnidex

  profiles:
    active: local

  threads:
    virtual:
      enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

    default-property-inclusion: non_null

    time-zone: UTC

  jpa:
    open-in-view: false

server:
  port: 8080

  error:
    include-message: always